//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neodym.Test.Properties {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class KalmanTestResources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal KalmanTestResources() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neodym.Test.Properties.KalmanTestResources", typeof(KalmanTestResources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		internal static byte[] Php {
			get {
				object obj = ResourceManager.GetObject("Php", resourceCulture);
				return ((byte[])(obj));
			}
		}
		
		internal static byte[] Phu {
			get {
				object obj = ResourceManager.GetObject("Phu", resourceCulture);
				return ((byte[])(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to 0.1.
		/// </summary>
		internal static string Q {
			get {
				return ResourceManager.GetString("Q", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to 30.0.
		/// </summary>
		internal static string r {
			get {
				return ResourceManager.GetString("r", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to 20.0.
		/// </summary>
		internal static string T {
			get {
				return ResourceManager.GetString("T", resourceCulture);
			}
		}
		
		internal static byte[] xhp {
			get {
				object obj = ResourceManager.GetObject("xhp", resourceCulture);
				return ((byte[])(obj));
			}
		}
		
		internal static byte[] xhu {
			get {
				object obj = ResourceManager.GetObject("xhu", resourceCulture);
				return ((byte[])(obj));
			}
		}
		
		internal static byte[] zks {
			get {
				object obj = ResourceManager.GetObject("zks", resourceCulture);
				return ((byte[])(obj));
			}
		}
	}
}
