//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

namespace MathNet.Filtering.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
#if NETSTANDARD1_3
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MathNet.Filtering.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
#else
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MathNet.Filtering.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
#endif
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerator and denominator vectors must contain the same number of elements..
        /// </summary>
        internal static string ArgumentCoefficientLengthMismatch {
            get {
                return ResourceManager.GetString("ArgumentCoefficientLengthMismatch", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Coefficient vector must not be empty..
        /// </summary>
        internal static string ArgumentEmptyCoefficientVector {
            get {
                return ResourceManager.GetString("ArgumentEmptyCoefficientVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even number of coefficients required..
        /// </summary>
        internal static string ArgumentEvenNumberOfCoefficients {
            get {
                return ResourceManager.GetString("ArgumentEvenNumberOfCoefficients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windowing function is not valid..
        /// </summary>
        internal static string InvalidWindowFunctionException {
            get {
                return ResourceManager.GetString("InvalidWindowFunctionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covariance Matrix must have same number of row/cols as state variable..
        /// </summary>
        internal static string KFCovarianceIncorrectSize {
            get {
                return ResourceManager.GetString("KFCovarianceIncorrectSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covariance matrix must be square..
        /// </summary>
        internal static string KFCovarianceNotSquare {
            get {
                return ResourceManager.GetString("KFCovarianceNotSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement covariance should be a square matrix with rows/cols equal to number of measurements..
        /// </summary>
        internal static string KFMeasureCovarainceMalformed {
            get {
                return ResourceManager.GetString("KFMeasureCovarainceMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurements should be a single column matrix..
        /// </summary>
        internal static string KFMeasurementVectorMalformed {
            get {
                return ResourceManager.GetString("KFMeasurementVectorMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement sensitivity matrix should contain same number of rows as measurement matrix and columns as there are state variables..
        /// </summary>
        internal static string KFMeasureSensitivityMalformed {
            get {
                return ResourceManager.GetString("KFMeasureSensitivityMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise coupling matrix should have number of rows equal to number of state variables, and columns equal to process noise rows..
        /// </summary>
        internal static string KFNoiseCouplingMalformed {
            get {
                return ResourceManager.GetString("KFNoiseCouplingMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise Covariance matrix should be square..
        /// </summary>
        internal static string KFNoiseCovarianceMalformed {
            get {
                return ResourceManager.GetString("KFNoiseCovarianceMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square noise covariance matrices should have same number of rows/cols as state variables..
        /// </summary>
        internal static string KFSquareNoiseCouplingMalformed {
            get {
                return ResourceManager.GetString("KFSquareNoiseCouplingMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalman Filter state must be a column vector..
        /// </summary>
        internal static string KFStateNotColumnVector {
            get {
                return ResourceManager.GetString("KFStateNotColumnVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Transition should be square matrix with same rows/cols as state variables..
        /// </summary>
        internal static string KFStateTransitionMalformed {
            get {
                return ResourceManager.GetString("KFStateTransitionMalformed", resourceCulture);
            }
        }
    }
}
