//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathNet.Symbolics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MathNet.Symbolics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the contract for the Math.NET Yttrium module {0} ({1}). It was expected at: &apos;{2}&apos;. You may want to check the mapping configuration file (usually yttrium.mapping.config)..
        /// </summary>
        internal static string BindingContractLoadFailed {
            get {
                return ResourceManager.GetString("BindingContractLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the factory for the Math.NET Yttrium module {0} ({1}). It was expected at: &apos;{2}&apos;. You may want to check the mapping configuration file (usually yttrium.mapping.config)..
        /// </summary>
        internal static string BindingFactoryLoadFailed {
            get {
                return ResourceManager.GetString("BindingFactoryLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown binding id {0}. Can&apos;t get a factory..
        /// </summary>
        internal static string BindingUnknownId {
            get {
                return ResourceManager.GetString("BindingUnknownId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown binding type {0}. Can&apos;t get a factory..
        /// </summary>
        internal static string BindingUnknownType {
            get {
                return ResourceManager.GetString("BindingUnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong type parameters. Can&apos;t get a factory for type {0}..
        /// </summary>
        internal static string BindingWrongTypeParameters {
            get {
                return ResourceManager.GetString("BindingWrongTypeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MathContext stack in illegal state. This indicates a programming error, please report..
        /// </summary>
        internal static string ContextIllegalState {
            get {
                return ResourceManager.GetString("ContextIllegalState", resourceCulture);
            }
        }
    }
}
